name: Bug Report
description: Report an anomaly or unexpected behavior.
# title: "[Bug: ]"
labels: "bug" 

body:
- type: markdown
  attributes:
    value: |
      - [x] Bug

      Thank you for reporting a bug! Use the sections below to submit a bug.  

      **NOTE:**
      - All bugs are welcome to be reported.
      - Remember to include sufficient details and context.
      - If you have multiple questions, suggestions, or bugs, please submit them in separate issues.  
      <br>
      Please provide the following details about the issue you encountered.  

# - type: input
#   id: logged-by
#   validations:
#     required: true
#   attributes:
#     label: Logged By 
#     description: |
#         Who found this issue?

- type: input
  id: reported-on
  attributes:
    label: Reported on
    description: |
      When was this bug encountered on?
    placeholder: YYYY-MM-DD
  validations:
    required: true
    pattern: "^\\d{4}-\\d{2}-\\d{2}$"
    message: "Please enter a valid date"

# - type: input
#   id: epic-features
#   validations:
#     required: true
#   attributes:
#     label: Epic Features
#     description: |
#         Where is the issue?

# - type: input
#   id: url
#   validations:
#     required: false
#   attributes:
#     label: URL, if applicable 
#     description: |
#         What is the URL of the page with the mentioned bug?

# - type: input
#   id: title
#   validations:
#     required: true
#   attributes:
#     label: Title
#     description: |
#         What is the issue?

- type: markdown
  attributes:
    value: |
      Now, please provide a clear & concise description of what the bug is.  

- type: input
  id: what-happened
  attributes:
    label: What happened?
    description: Describe what went wrong.
  validations:
    required: true

# - type: dropdown
#   id: severity
#   validations:
#     required: true
#   attributes:
#     label: Severity
#     description: |
#         How severe is this issue?
#     options : 
#       - High 
#       - Medium
#       - Low

# - type: input
#   id: Environment
#   validations:
#     required: false
#   attributes:
#     label: Environment
#     description: |
#         Tell us about the environment.

- type: textarea
  id: screenshots
  attributes:
    label: Screenshot(s)
    description: Show us what the issue is. Either select the files you want or simply drag and drop files here.
  validations:
    required: true

- type: input
  id: how-to-reproduce
  attributes:
    label: How to reproduce?
    description: Tell us how to reproduce the issue!
  validations:
    required: false

- type: input
  id: expected-behavior
  attributes:
    label: Expected Behavior
    description: Tell us what you expected to see!
    placeholder: 
  validations:
    required: false

    
