name: Bug Report
description: Report an anomaly or unexpected behavior.
title: "[Bug]: "
labels: "bug" 

body:
- type: markdown
  attributes:
    value: |
      - [x] Bug

      Thank you for reporting a bug! Use the sections below to submit a bug. 

      **NOTE:**
      - All bugs are welcome to be reported.
      - Remember to include sufficient details and context.
      - If you have multiple questions, suggestions, or bugs, please submit them in separate issues.


      Please provide the following details about the issue you encountered.  

- type: input
  id: author
  validations:
    required: true
  attributes:
    label: Logged By 
    description: |
        Who found this issue?

- type: input
  id: feature
  validations:
    required: true
  attributes:
    label: Epic Features
    description: |
        Where is the issue?

- type: input
  id: title
  validations:
    required: true
  attributes:
    label: Title
    description: |
        What is the issue?

- type: markdown
  attributes:
    value: |
      Now, please provide a clear & concise description of what the bug is.  

- type: textarea
  id: what-happened
  attributes:
    label: What happened?
    description: Describe the observed behavior. Insert image if possible.
    placeholder: Tell us what you see!
  validations:
    required: true

- type: input
  id: severity
  validations:
    required: true
  attributes:
    label: Severity
    description: |
        How severe is this issue?

- type: input
  id: Environment
  validations:
    required: true
  attributes:
    label: Environment
    description: |
        Tell us about the environment.
    

- type: textarea
  id: expected
  attributes:
    label: Expected Behavior
    description: What did you expect to happen?
    placeholder: Tell us what you expected to see!
  validations:
    required: true
