name: Bug Report
description: Report an anomaly or unexpected behavior.
labels: "bug" 

body:
- type: markdown
  attributes:
    value: |
      - [x] Bug

      Thank you for reporting a bug! Use the sections below to submit a bug.  

      **NOTE:**
      - All bugs are welcome to be reported.
      - Remember to include sufficient details and context.
      - If you have multiple questions, suggestions, or bugs, please submit them in separate issues.  
      <br>
      Please provide the following details about the issue you encountered.  

- type: input
  id: logged-by
  validations:
    required: true
  attributes:
    label: Logged By 
    description: Who found this issue?

- type: input
  id: reported-on
  validations:
    required: false
  attributes:
    label: Reported on
    description: When was this bug encountered on?
    placeholder: YYYY-MM-DD

- type: input
  id: epic-features
  validations:
    required: true
  attributes:
    label: Epic Features
    description: Where is the issue?

- type: input
  id: url
  validations:
    required: false
  attributes:
    label: URL, if applicable 
    description: What is the URL of the page with the mentioned bug?

- type: input
  id: describe
  validations:
    required: true
  attributes:
    label: Description
    description: What is the issue?

- type: dropdown
  id: severity
  validations:
    required: true
  attributes:
    label: Severity
    description: How severe is this issue?
    options : 
      - High 
      - Medium
      - Low

- type: dropdown
  id: environment
  validations:
    required: true
  attributes:
    label: Environment
    description: Which environment is this issue on?
    options : 
      - Dev 
      - Staging
      - Production

- type: textarea
  id: screenshots
  validations:
    required: true
  attributes:
    label: Screenshot(s)
    description: Show us what the issue is. Either select the files you want or simply drag and drop files here.

- type: input
  id: how-to-reproduce
  validations:
    required: false
  attributes:
    label: How to reproduce?
    description: Tell us how to reproduce the issue!

- type: input
  id: expected-behavior
  validations:
    required: false
  attributes:
    label: Expected Behavior
    description: Tell us what you expected to see!
