name: Bug Report
description: Report an anomaly or unexpected behavior.
title: "[Bug]: "
labels: "bug" 

body:
- type: markdown
  attributes:
    value: |
      - [x] Bug

      Thank you for reporting a bug! Use the sections below to submit a bug. 
      
      - All bugs are welcome to be reported.
      - Remember to include sufficient details and context.
      - If you have multiple questions, suggestions, or bugs, please submit them in separate issues.

      Please provide the following details about the issue you encountered.  

- type: input
  id: author
  validations:
    required: true
  attributes:
    label: Logged By 

- type: input
  id: authors
  validations:
    required: true
  attributes:
    label: Author(s)
    description: |
        Who wrote the sample?
        
        Because of the way this repository is configured, samples authors do not get a notification when you create an issue. 
        
        For the section above **@mention any author of the sample**. Authors' GitHub handle can be found on the main sample documentation page, under the "Solution" section. 
        
        Issues without an @mention will be closed automatically, as authors won't get notified.
        
        **NOTE:** Don't @mention the repo maintainers, they already get notified.

- type: markdown
  attributes:
    value: |
      Provide a clear & concise description of what the bug is. Please follow our guidance on [How To Create Good Issues](https://github.com/pnp/powerfx-samples/wiki/How-to-Create-Good-Issues) which explains how to apply formatting, adding references & resources, screenshots, etc. 
      
      **Do not attach ZIP files** of your code or compiled projects - instead, please publish your code to a public GitHub repo & post a link to it.

- type: textarea
  id: what-happened
  attributes:
    label: What happened?
    description: Describe the observed behavior
    placeholder: Tell us what you see!
  validations:
    required: true

- type: textarea
  id: steps
  attributes:
    label: Steps to reproduce
    description: How do you reproduce this? Please provide as much step-by-step detail as possible.
    value: |
      1.
      2.
      3.
  validations:
    required: true

- type: textarea
  id: expected
  attributes:
    label: Expected behavior
    description: What did you expect to happen when the reproduce steps are followed?
    placeholder: Tell us what you expected to see!
  validations:
    required: true
