name: Extract Issue Form Values

on:
  issues:
    types: [opened, edited]

jobs:
  extract-values:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract values from issue form
        id: extract_values
        uses: actions/github-script@v4
        with:
          script: |
            const issue = context.payload.issue;
            const formFields = {
              'Logged by': 'logged-by',
              'Reported on': 'reported-on',
              'Epic - Features': 'epic-features'
              'URL': 'url'
              'Severity': 'severity'
              'Environment': 'environment'
            };
            const extractedValues = {};
            Object.keys(formFields).forEach((fieldName) => {
              const fieldId = formFields[fieldName];
              if (issue && issue.body && issue.body.input_fields && issue.body.input_fields[fieldId]) {
                extractedValues[fieldName] = issue.body.input_fields[fieldId].value;
              }
            });
            return extractedValues;

      - name: Log extracted values
        run: |
          echo "Logged by: ${{ steps.extract_values.outputs['Logged by'] }}"
          echo "Reported on: ${{ steps.extract_values.outputs['Reported on'] }}"
          echo "Epic - features: ${{ steps.extract_values.outputs['Epic - Features'] }}"
          echo "URL: ${{ steps.extract_values.outputs['URL'] }}"
          echo "Severity: ${{ steps.extract_values.outputs['Severity'] }}"
          echo "Environment: ${{ steps.extract_values.outputs['Environment'] }}"
          console.log('This is running')
