name: Populate Project Fields
on:
  issues:
    types: [opened, edited]

jobs:
  populate-fields:
    runs-on: ubuntu-latest
    steps:
      - name: Check if issue has custom fields
        id: check_fields
        uses: actions/github-script@v4
        with:
          script: |
            const fields = context.payload.issue.body;
            const customFields = {
              'Logged by': 'logged-by',
              'Reported on': 'reported-on',
              'Epic Features': 'epic-features',
              'URL': 'url',
              'Severity': 'severity',
              'Environment': 'environment'
            };
            const fieldsToUpdate = {};
            Object.keys(customFields).forEach((customField) => {
              const fieldId = customFields[customField];
              if (fields && fields[fieldId]) {
                fieldsToUpdate[customField] = fields[fieldId];
              }
            });
            console.log(fieldsToUpdate); // Output fieldsToUpdate for debugging
            return { fieldsToUpdate }; // Return fieldsToUpdate as an object
      - name: Update project card
        uses: actions/github-script@v4
        with:
          script: |
            const projectNumber = 1; // Replace with your project number
            const columnName = 'To do'; // Replace with your column name
            const fieldsToUpdate = steps.check_fields.outputs.fieldsToUpdate; // Access fieldsToUpdate from the check_fields step output
            console.log(fieldsToUpdate); // Output fieldsToUpdate for debugging
            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
