name: Extract Issue Form Values

on:
  issues:
    types: [opened, edited]

jobs:
  extract-values:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract values from issue form
        id: extract_values
        uses: actions/github-script@v4
        with:
          script: |
            const issue = context.payload.issue;
            const formFields = {
              'Field 1': 'field-1',
              'Field 2': 'field-2',
              'Field 3': 'field-3'
            };
            const extractedValues = {};
            Object.keys(formFields).forEach((fieldName) => {
              const fieldId = formFields[fieldName];
              if (issue && issue.body && issue.body.input_fields && issue.body.input_fields[fieldId]) {
                extractedValues[fieldName] = issue.body.input_fields[fieldId].value;
              }
            });
            return extractedValues;

      - name: Log extracted values
        run: |
          echo "Field 1: ${{ steps.extract_values.outputs['Field 1'] }}"
          echo "Field 2: ${{ steps.extract_values.outputs['Field 2'] }}"
          echo "Field 3: ${{ steps.extract_values.outputs['Field 3'] }}"
